import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";

const BeVietnamPro = Be_Vietnam_Pro({
  weight: ["400", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Pro2col",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={BeVietnamPro.className}>{children}</body>
    </html>
  );
}
